# Hardware configuration for Arch Linux desktop
# This file will be auto-generated by nixos-generate-config
# when you actually install on the hardware
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  
  # This will be populated by nixos-generate-config
  # based on your actual hardware
  
  # Example configuration (will be replaced):
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];  # or "kvm-intel" for Intel
  boot.extraModulePackages = [ ];
  
  # CPU configuration
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # OR for Intel:
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Enable firmware updates
  services.fwupd.enable = true;
}