"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = [
    "<C-q>",
  ], run = "close", desc = "Close" },
  { on = [
    "<C-c>",
  ], run = "close", desc = "Close" },
]

append_keymap = [
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config", desc = "Go to the Config dir" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/.config/nvim", desc = "Go to the nvim config" },
  { on = [
    "g",
    "f",
  ], run = "cd ~/.config/fish", desc = "Go to the fish config" },
  { on = [
    "<C-p>",
  ], run = "seek -5", desc = "Scroll preview down" },
  { on = [
    "<C-n>",
  ], run = "seek 5", desc = "Scroll preview up" },
]
