"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = [
    "<C-q>",
  ], run = "close", desc = "Close" },
  { on = [
    "<C-c>",
  ], run = "close", desc = "Close" },
  { on = [
    "f",
    "g",
  ], run = "plugin fg", desc = "Find file by content (fuzzy match)" },
  { on = [
    "f",
    "G",
  ], run = "plugin fg --args='rg'", desc = "Find file by content (ripgrep match)" },
  { on = [
    "f",
    "f",
  ], run = "plugin fg --args='fzf'", desc = "Find file by filename" },
]

append_keymap = [
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config/yazi", desc = "Go to the Config dir" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/.config/nvim", desc = "Go to the nvim config" },
  { on = [
    "g",
    "f",
  ], run = "cd ~/.config/fish", desc = "Go to the fish config" },
  { on = [
    "<C-p>",
  ], run = "seek -5", desc = "Scroll preview down" },
  { on = [
    "<C-n>",
  ], run = "seek 5", desc = "Scroll preview up" },
]
