# yazi.toml
[manager]
ratio = [1, 1, 2]

[opener]
# edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
edit = [{ run = 'zellij run -c -i -- nvim $1', desc = "Open File in a new pane" }]
