"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 1, 2]
sort_by = "natural"
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true

[preview]
max_width = 1200
max_height = 1000

[opener]
edit = [{ run = 'zellij edit -i "$1"', desc = "Open File in the same pane" }]
